### PR TITLE
Creates RoundRobin Scheduling Functionality

### PR DESCRIPTION
**Pull request by Areax**
Branches off of Tyler's FIFO branch.
Fixes a few bugs from that branch and implements RoundRobin scheduling instead of FIFO scheduling.

### CODE REVIEW

**Review by nko12 — CHANGES_REQUESTED** [review]
This is looking very good, but did you test with more than just the input file the professor provided? While this works with the single input file the professor provided, it hits a segmentation fault when I use another RoundRobin input file. I'll provide the sample file after this comment.

Some other notes:
- Please remove Tyler's files `FirstComeFirstServe.h` and `FirstComeFirstServe.c` from this commit since this commit is for your code, his code does not compile, and he will be making changes to it. Merging this commit will cause conflicts for him later when he makes a pull request for his code.
- You will need to rename `RunProcess` to something else, probably `RunRoundRobinProcess` or `RunRRProcess`. When `RoundRobin.h` and `FirstComeFirstServe.h` are included in the main file, there will be a linker error because two functions would have the same name.
- I would prefer we not use `#ifdef #endif` header guards; `#pragma once` is a cleaner and more modern header guard and doesn't add unnecessary macros for the compiler to worry about.

**Comment by nko12** [comment]
The following file is the `processes.in` version of the round robin question in optional homework 1. You should test your code with this file.
```
processcount 5        # Read 5 processes
runfor 32             # Run for 15 time units
use rr                # Can be fcfs, sjf, or rr
quantum 3             # Time quantum – only if using rr
process name P1 arrival 1 burst 6
process name P2 arrival 3 burst 12
process name P3 arrival 5 burst 2
process name P4 arrival 7 burst 8
process name P5 arrival 9 burst 3
end
```

The segmentation fault occurs on line 44 of `RoundRobin.c`. At the time of the fault, gdb reports the value of `Queue[Head % numProc]` is 194, which causes an index out of bounds exception in C++ and a segmentation fault in C.

**Comment by Areax** [comment]
Fixes changes per nko12's request.  Code now is a little more repetitive due to checking if a process is available twice, but I don't know if there's a way around that.

**Review by nko12 — CHANGES_REQUESTED** [review]
We're still not quite there yet. Hopefully this is a small fix, but the second example file I used [above](https://github.com/pH34r-pH/Classwork/pull/4#issuecomment-363659010) still does not produce the correct output. Next comment I'll describe this more.

Some other small things:
- Please remove `FirstComeFirstServe.c` and `FirstComeFirstServe.h` from your commits. Keeping these may cause merge issues for Tyler when he's ready to submit his pull request.
- `RunRRProcess` should return void.

**Comment by nko12** [comment]
Your output appears to become incorrect starting at time 7.

```
...
Time 4: P2 selected (burst 12)
Time 5: P3 arrived
Time 7: P4 arrived
Time 7: P1 selected (burst 3)
Time 9: P5 arrived
Time 10: P1 finished
...
```

At time 7, process 4 arrives and _process 3_ should be selected, not process 1. As an additional check, I looked at the wait and turnaround times that were calculated as well.

```
P1 wait 3 turnaround 9
P2 wait 17 turnaround 29
P3 wait 5 turnaround 7
P4 wait 14 turnaround 22
P5 wait 9 turnaround 12
```

Those should be:

```
P1 wait 11 turnaround 17
P2 wait 17 turnaround 29
P3 wait 2 turnaround 4
P4 wait 14 turnaround 22
P5 wait 3 turnaround 6
```

You can verify this against the [COP4600 Optional HW 1](https://webcourses.ucf.edu/files/64910665/download?download_frd=1) solution file.

**Review by nko12 — APPROVED** [review]
Great job Jasper. The good news is, I approve of your changes. I made my own test case and it passed it properly. **Please wait for @pH34r-pH's  approval before you merge.** The bad news is, the algorithm is still not actually quite right, nor is Tyler's.

Your code produces incorrect output if the processes are not _listed_ in the order they arrived. In other words, while this produces correct output.
```
process name P1 arrival 1 burst 6
process name P2 arrival 3 burst 12
process name P3 arrival 5 burst 2
process name P4 arrival 7 burst 8
process name P5 arrival 9 burst 3
```
This ordering produces incorrect output.
```
process name P5 arrival 9 burst 3
process name P2 arrival 3 burst 12
process name P3 arrival 5 burst 2
process name P4 arrival 7 burst 8
process name P1 arrival 1 burst 6
```

From the assignment specification: "Note that the processes do not need to be specified in order of arrival, and do not need to have similar names."

The easiest way to deal with this is to sort the lists by arrival time, but since this is C, there are no sort functions. What I'll do is implement one and have the parser sort the processes by arrival time before the file reading function returns. That way, the algorithms are guaranteed in-order arrival of processes.

**Review by pH34r-pH — APPROVED** [review]

**Pull request merged**
